### ISSUE TITLE
i think i have a gpu but it doesn't recognize it

### ISSUE THREAD

**Issue by sctech-tr** [ufuayk/brofetch#1]
what
![ss](https://github.com/user-attachments/assets/a4266ee9-9f66-49b7-a09f-c701cc4d8350)

my gpu is:  
```
NVIDIA GeForce GTX 660M  
```
in case you need it

**Comment by ufuayk** [comment]
I made a change in the gpu variable and this problem should have disappeared. 
*I would appreciate if you could test again and tell me the output.*
